### ISSUE TITLE
Application crash on opening.

### ISSUE THREAD

**Issue by franco27** [IacobIonut01/Gallery#475]
Hello,

Since the update to version 3.0.1-30101, your application no longer opens.

1. I click on the icon on the mobile phone screen.
2. The app tries to open but closes immediately. 
I see the window for one or two seconds before it closes.
3. I do not receive any error message from Android 14.

With this version, I cleared the user data from the Android settings, and I was able to open it afterwards.

I have just updated to version 3.0.1-30102 Nightly Release. This same problem has reappeared, and I am currently unable to open your application.

Can you please fix this issue?

My system is running Android 14. I did not have this problem before.

**Comment by franco27** [comment]
My system configuration is as follows:
motorola moto g54 5G
Android 14 API Level 34.
Mediatek MT6855V/AZA
arm64-v8a, armeabi-v7a, armeabi
64 Bit, 8 Cores
2400 x 1080 pixels (FHD+)
6.5 pouces | 120,0 Hz
400 dpi (XHDPI)

**Comment by IacobIonut01** [comment]
Fixed in https://github.com/IacobIonut01/Gallery/commit/33d972c0b4a87e4723f0a5e744ab5836097094fd

**Comment by inferenceus** [comment]
I have installed Gallery version 3.0.0-30103 nightly release and the crashing still occurs when attempting to open the app via tapping an image in another app. While the app does open when using its icon, it seems the IPC share functionality is still crashing.

**Device:** Google Pixel 8 Pro
**Operating system:** Android 14 (GrapheneOS)
**Gallery version:** 3.0.0-30103

**Comment by IacobIonut01** [comment]
That's for another reason, I'll check in a bit

**Comment by franco27** [comment]
For me, it was resolved with version Gallery-3.0.1-30103.apk.

**Comment by inferenceus** [comment]
Gallery version 3.0.1-30104 has resolved the issue. Thank you for your quick response in resolving this issue.
